# -*- coding: utf-8 -*-
"""
Created on Wed Mar 02 18:28:43 2016

@author: wxt
"""

"""
Problem 2:

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.


"""
def fib(a, b, maxnum = 4000000):
    
    while a <= maxnum:
        if a % 2 == 0:
            yield a
        a, b = b, a + b

if __name__ == '__main__':
    
    gen = fib(1, 2)
    print sum(gen)